# 网关转发服务配置文件
# 配置服务端口、日志、监控和转发规则
# 
# @author Baoleme Team
# @version 1.0
# @since 2025-01-25

# 服务器配置
server:
  port: 8090
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-connections: 8192
    accept-count: 100

# Spring配置
spring:
  application:
    name: gateway-forward-service
  
  # Web配置
  web:
    resources:
      add-mappings: false
  
  # Jackson配置
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 日志配置
logging:
  level:
    org.demo.gateway.forward: INFO
    org.springframework.web: DEBUG
    org.apache.http: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway-forward-service.log
    max-size: 100MB
    max-history: 30

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:

# 微服务路由配置
gateway:
  forward:
    # 微服务端点配置
    services:
      admin-service:
        url: http://localhost:8084
        health-check: /actuator/health
        timeout: 30000
      user-service:
        url: http://localhost:8081
        health-check: /actuator/health
        timeout: 30000
      merchant-service:
        url: http://localhost:8082
        health-check: /actuator/health
        timeout: 30000
      rider-service:
        url: http://localhost:8083
        health-check: /actuator/health
        timeout: 30000
      common-service:
        url: http://localhost:8085
        health-check: /actuator/health
        timeout: 30000
      gateway-service:
        url: http://localhost:8080
        health-check: /actuator/health
        timeout: 30000
    
    # 路由映射规则
    routes:
      # 管理员服务路由
      - path: "/admin/**"
        service: admin-service
        strip-prefix: false
      
      # 用户服务路由
      - path: "/user/**"
        service: user-service
        strip-prefix: false
      
      # 商家服务路由
      - path: "/merchant/**"
        service: merchant-service
        strip-prefix: false
      
      # 店铺服务路由
      - path: "/store/**"
        service: merchant-service
        strip-prefix: false
      
      # 商品服务路由
      - path: "/product/**"
        service: merchant-service
        strip-prefix: false
      
      # 骑手服务路由
      - path: "/rider/**"
        service: rider-service
        strip-prefix: false
      
      # 图片上传路由
      - path: "/image/**"
        service: rider-service
        strip-prefix: false
      
      # 订单服务路由
      - path: "/orders/**"
        service: common-service
        strip-prefix: false
      
      # 支付服务路由
      - path: "/payment/**"
        service: common-service
        strip-prefix: false
      
      # 通知服务路由
      - path: "/notification/**"
        service: common-service
        strip-prefix: false
      
      # 评论服务路由
      - path: "/reviews/**"
        service: common-service
        strip-prefix: false
      
      # 优惠券服务路由
      - path: "/coupons/**"
        service: common-service
        strip-prefix: false
      
      # 数据库API路由
      - path: "/api/database/**"
        service: gateway-service
        strip-prefix: false
    
    # 连接池配置
    connection-pool:
      max-total: 200
      max-per-route: 50
      connection-timeout: 5000
      socket-timeout: 30000
      connection-request-timeout: 5000
      validate-after-inactivity: 2000
    
    # 重试配置
    retry:
      max-attempts: 3
      delay: 1000
      multiplier: 2.0
    
    # 熔断配置
    circuit-breaker:
      failure-threshold: 5
      timeout: 60000
      reset-timeout: 30000