spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/baoleme?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 88159918
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      location: /root/workspace/Baoleme
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    upload-dir: upload
    base-url: /images/