spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://localhost:3306/baoleme?useSSL=false&serverTimezone=UTC
    username: root
    password: 88159918
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      location: /Users/mawenban/Desktop/Yuan/GitHub-res/Baoleme/Baoleme
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    # 物理存储根目录，指向项目根目录下的 upload/（如果用相对路径，请确保 Spring Boot 启动时的当前工作目录是项目根目录）
    upload-dir: upload
    # 前端/浏览器访问时的前缀：例如客户端请求 http://localhost:8080/images/xxx.jpg，
    # 就会映射到本地项目根目录下 upload/xxx.jpg
    base-url: /images/